name: znn_ledger_dart
description: Ledger Wallet for Zenon Dart SDK
publish_to: none
version: 0.0.2

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  convert: ^3.0.2
  ffi: ^2.0.0
  hex: ^0.2.0
  path: ^1.8.2
  logging: ^1.2.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  znn_sdk_dart:
    git:
      url: https://github.com/zenon-network/znn_sdk_dart.git
      ref: 5967f385f6d64dcf61068485674a9e079534e68b

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  lints: ^3.0.0
  test: ^1.24.4